### ISSUE TITLE
Bio version

### ISSUE THREAD

**Issue by banma12956** [RiversDong/AcrDetector#1]
Hi! I directly ran 'python AcrDetector.py -i xx.fasta -o xx' and python reported
`"Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.`

Could you please specify the version of Bio? Thank you!

**Comment by RiversDong** [comment]
Hello 
Biopython version >= 1.77
The script is tested in python 3.7
if you have further questions about AcrDetector please email to me chuand@whu.edu.cn so that I can response you immediately
Best
